version: '3.8'

services:
  ecomart-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./backend/products.csv:/app/products.csv
    restart: unless-stopped

  ecomart-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - ecomart-app
    restart: unless-stopped